"""
app/database/base.py
--------------------
SQLAlchemy declarative base and shared column helpers.

All ORM models must import ``Base`` from this module so Alembic's
auto-generate can discover every table in a single metadata object.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Shared declarative base for every ORM model in the platform.

    Every concrete model inherits from this class, which ensures all tables
    are registered under the same ``MetaData`` instance — required for
    Alembic auto-generation to work correctly.
    """

    # ── Common columns shared by every table ───────────────────────────────────

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        comment="Universally unique identifier generated by the database.",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Timestamp of record creation (UTC, set by the database).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Timestamp of the most recent update (UTC, maintained by the ORM).",
    )
